code --install-extension geddski.macros
code --install-extension DotJoshJohnson.xml
code --install-extension hollowtree.vue-snippets
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension redhat.vscode-yaml
code --install-extension naumovs.color-highlight
code --install-extension wayou.vscode-todo-highlight
code --install-extension Gruntfuggly.todo-tree
code --install-extension akamud.vscode-theme-onedark
code --install-extension mkloubert.vscode-remote-workspace
code --install-extension vsmobile.vscode-react-native
code --install-extension DougFinke.vscode-pandoc
code --install-extension eg2.vscode-npm-script
code --install-extension vscjava.vscode-maven
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension vadimcn.vscode-lldb
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-java-debug
code --install-extension robertohuertasm.vscode-icons
code --install-extension dbaeumer.vscode-eslint
code --install-extension PeterJausovec.vscode-docker
code --install-extension bajdzis.vscode-database
code --install-extension deerawan.vscode-dash
code --install-extension vsciot-vscode.vscode-arduino
code --install-extension Equinusocio.vsc-material-theme
code --install-extension fallenwood.vimL
code --install-extension vscodevim.vim
code --install-extension octref.vetur
code --install-extension eg2.tslint
code --install-extension robinbentley.sass-indented
code --install-extension rebornix.ruby
code --install-extension humao.rest-client
code --install-extension TroelsDamgaard.reflow-paragraph
code --install-extension mechatroner.rainbow-csv
code --install-extension Hridoy.rails-snippets
code --install-extension WallabyJs.quokka-vscode
code --install-extension ms-python.python
code --install-extension esbenp.prettier-vscode
code --install-extension ms-vscode.PowerShell
code --install-extension christian-kohler.path-intellisense
code --install-extension IBM.output-colorizer
code --install-extension ms-vscode.node-debug2
code --install-extension Angular.ng-template
code --install-extension ms-mssql.mssql
code --install-extension ms-vscode.mono-debug
code --install-extension metaseed.metago
code --install-extension Gimly81.matlab
code --install-extension zhuangtongfa.Material-theme
code --install-extension PKief.material-icon-theme
code --install-extension yzhang.markdown-all-in-one
code --install-extension James-Yu.latex-workshop
code --install-extension dbaeumer.jshint
code --install-extension xabikos.JavaScriptSnippets
code --install-extension redhat.java
code --install-extension Asuka.insertnumbers
code --install-extension abusaidm.html-snippets
code --install-extension Zignd.html-css-class-completion
code --install-extension ms-vscode.Go
code --install-extension Gruntfuggly.global-config
code --install-extension eamodio.gitlens
code --install-extension donjayamanne.githistory
code --install-extension felipecaputo.git-project-manager
code --install-extension EditorConfig.EditorConfig
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension Dart-Code.dart-code
code --install-extension ms-vscode.cpptools
code --install-extension Shan.code-settings-sync
code --install-extension formulahendry.code-runner
code --install-extension austin.code-gnu-global
code --install-extension avli.clojure
code --install-extension xaver.clang-format
code --install-extension wmaurer.change-case
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension HookyQR.beautify
code --install-extension ms-vscode.azure-account
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.auto-close-tag
code --install-extension ms-python.anaconda-extension-pack
code --install-extension annsk.alignment
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension GitHub.vscode-pull-request-github
code --install-extension vscode-org-mode.org-mode
code --install-extension Ikuyadeu.r-pack
