code-insiders --install-extension geddski.macros --force
code-insiders --install-extension DotJoshJohnson.xml --force
code-insiders --install-extension hollowtree.vue-snippets --force
code-insiders --install-extension ms-vsliveshare.vsliveshare --force
code-insiders --install-extension redhat.vscode-yaml --force
code-insiders --install-extension naumovs.color-highlight --force
code-insiders --install-extension wayou.vscode-todo-highlight --force
code-insiders --install-extension Gruntfuggly.todo-tree --force
code-insiders --install-extension akamud.vscode-theme-onedark --force
code-insiders --install-extension mkloubert.vscode-remote-workspace --force
code-insiders --install-extension vsmobile.vscode-react-native --force
code-insiders --install-extension DougFinke.vscode-pandoc --force
code-insiders --install-extension eg2.vscode-npm-script --force
code-insiders --install-extension vscjava.vscode-maven --force
code-insiders --install-extension DavidAnson.vscode-markdownlint --force
code-insiders --install-extension vadimcn.vscode-lldb --force
code-insiders --install-extension vscjava.vscode-java-test --force
code-insiders --install-extension vscjava.vscode-java-debug --force
code-insiders --install-extension robertohuertasm.vscode-icons --force
code-insiders --install-extension dbaeumer.vscode-eslint --force
code-insiders --install-extension PeterJausovec.vscode-docker --force
code-insiders --install-extension bajdzis.vscode-database --force
code-insiders --install-extension deerawan.vscode-dash --force
code-insiders --install-extension vsciot-vscode.vscode-arduino --force
code-insiders --install-extension Equinusocio.vsc-material-theme --force
code-insiders --install-extension fallenwood.vimL --force
code-insiders --install-extension vscodevim.vim --force
code-insiders --install-extension octref.vetur --force
code-insiders --install-extension eg2.tslint --force
code-insiders --install-extension robinbentley.sass-indented --force
code-insiders --install-extension rebornix.ruby --force
code-insiders --install-extension humao.rest-client --force
code-insiders --install-extension TroelsDamgaard.reflow-paragraph --force
code-insiders --install-extension mechatroner.rainbow-csv --force
code-insiders --install-extension Hridoy.rails-snippets --force
code-insiders --install-extension WallabyJs.quokka-vscode --force
code-insiders --install-extension ms-python.python --force
code-insiders --install-extension esbenp.prettier-vscode --force
code-insiders --install-extension ms-vscode.PowerShell --force
code-insiders --install-extension christian-kohler.path-intellisense --force
code-insiders --install-extension IBM.output-colorizer --force
code-insiders --install-extension ms-vscode.node-debug2 --force
code-insiders --install-extension Angular.ng-template --force
code-insiders --install-extension ms-mssql.mssql --force
code-insiders --install-extension ms-vscode.mono-debug --force
code-insiders --install-extension metaseed.metago --force
code-insiders --install-extension Gimly81.matlab --force
code-insiders --install-extension zhuangtongfa.Material-theme --force
code-insiders --install-extension PKief.material-icon-theme --force
code-insiders --install-extension yzhang.markdown-all-in-one --force
code-insiders --install-extension James-Yu.latex-workshop --force
code-insiders --install-extension dbaeumer.jshint --force
code-insiders --install-extension xabikos.JavaScriptSnippets --force
code-insiders --install-extension redhat.java --force
code-insiders --install-extension Asuka.insertnumbers --force
code-insiders --install-extension abusaidm.html-snippets --force
code-insiders --install-extension Zignd.html-css-class-completion --force
code-insiders --install-extension ms-vscode.Go --force
code-insiders --install-extension Gruntfuggly.global-config --force
code-insiders --install-extension eamodio.gitlens --force
code-insiders --install-extension donjayamanne.githistory --force
code-insiders --install-extension felipecaputo.git-project-manager --force
code-insiders --install-extension EditorConfig.EditorConfig --force
code-insiders --install-extension msjsdiag.debugger-for-chrome --force
code-insiders --install-extension Dart-Code.dart-code --force
code-insiders --install-extension ms-vscode.cpptools --force
code-insiders --install-extension Shan.code-settings-sync --force
code-insiders --install-extension formulahendry.code-runner --force
code-insiders --install-extension austin.code-gnu-global --force
code-insiders --install-extension avli.clojure --force
code-insiders --install-extension xaver.clang-format --force
code-insiders --install-extension wmaurer.change-case --force
code-insiders --install-extension CoenraadS.bracket-pair-colorizer --force
code-insiders --install-extension HookyQR.beautify --force
code-insiders --install-extension ms-vscode.azure-account --force
code-insiders --install-extension formulahendry.auto-rename-tag --force
code-insiders --install-extension formulahendry.auto-close-tag --force
code-insiders --install-extension ms-python.anaconda-extension-pack --force
code-insiders --install-extension annsk.alignment --force
code-insiders --install-extension ms-vscode-remote.vscode-remote-extensionpack --force
code-insiders --install-extension GitHub.vscode-pull-request-github --force
