code-insiders --install-extension geddski.macros
code-insiders --install-extension DotJoshJohnson.xml
code-insiders --install-extension hollowtree.vue-snippets
code-insiders --install-extension ms-vsliveshare.vsliveshare
code-insiders --install-extension redhat.vscode-yaml
code-insiders --install-extension naumovs.color-highlight
code-insiders --install-extension wayou.vscode-todo-highlight
code-insiders --install-extension Gruntfuggly.todo-tree
code-insiders --install-extension akamud.vscode-theme-onedark
code-insiders --install-extension mkloubert.vscode-remote-workspace
code-insiders --install-extension vsmobile.vscode-react-native
code-insiders --install-extension DougFinke.vscode-pandoc
code-insiders --install-extension eg2.vscode-npm-script
code-insiders --install-extension vscjava.vscode-maven
code-insiders --install-extension DavidAnson.vscode-markdownlint
code-insiders --install-extension vadimcn.vscode-lldb
code-insiders --install-extension vscjava.vscode-java-test
code-insiders --install-extension vscjava.vscode-java-debug
code-insiders --install-extension robertohuertasm.vscode-icons
code-insiders --install-extension dbaeumer.vscode-eslint
code-insiders --install-extension PeterJausovec.vscode-docker
code-insiders --install-extension bajdzis.vscode-database
code-insiders --install-extension deerawan.vscode-dash
code-insiders --install-extension vsciot-vscode.vscode-arduino
code-insiders --install-extension Equinusocio.vsc-material-theme
code-insiders --install-extension fallenwood.vimL
code-insiders --install-extension vscodevim.vim
code-insiders --install-extension octref.vetur
code-insiders --install-extension eg2.tslint
code-insiders --install-extension robinbentley.sass-indented
code-insiders --install-extension rebornix.ruby
code-insiders --install-extension humao.rest-client
code-insiders --install-extension TroelsDamgaard.reflow-paragraph
code-insiders --install-extension mechatroner.rainbow-csv
code-insiders --install-extension Hridoy.rails-snippets
code-insiders --install-extension WallabyJs.quokka-vscode
code-insiders --install-extension ms-python.python
code-insiders --install-extension esbenp.prettier-vscode
code-insiders --install-extension ms-vscode.PowerShell
code-insiders --install-extension christian-kohler.path-intellisense
code-insiders --install-extension IBM.output-colorizer
code-insiders --install-extension ms-vscode.node-debug2
code-insiders --install-extension Angular.ng-template
code-insiders --install-extension ms-mssql.mssql
code-insiders --install-extension ms-vscode.mono-debug
code-insiders --install-extension metaseed.metago
code-insiders --install-extension Gimly81.matlab
code-insiders --install-extension zhuangtongfa.Material-theme
code-insiders --install-extension PKief.material-icon-theme
code-insiders --install-extension yzhang.markdown-all-in-one
code-insiders --install-extension James-Yu.latex-workshop
code-insiders --install-extension dbaeumer.jshint
code-insiders --install-extension xabikos.JavaScriptSnippets
code-insiders --install-extension redhat.java
code-insiders --install-extension Asuka.insertnumbers
code-insiders --install-extension abusaidm.html-snippets
code-insiders --install-extension Zignd.html-css-class-completion
code-insiders --install-extension ms-vscode.Go
code-insiders --install-extension Gruntfuggly.global-config
code-insiders --install-extension eamodio.gitlens
code-insiders --install-extension donjayamanne.githistory
code-insiders --install-extension felipecaputo.git-project-manager
code-insiders --install-extension EditorConfig.EditorConfig
code-insiders --install-extension msjsdiag.debugger-for-chrome
code-insiders --install-extension Dart-Code.dart-code
code-insiders --install-extension ms-vscode.cpptools
code-insiders --install-extension Shan.code-settings-sync
code-insiders --install-extension formulahendry.code-runner
code-insiders --install-extension austin.code-gnu-global
code-insiders --install-extension avli.clojure
code-insiders --install-extension xaver.clang-format
code-insiders --install-extension wmaurer.change-case
code-insiders --install-extension CoenraadS.bracket-pair-colorizer
code-insiders --install-extension HookyQR.beautify
code-insiders --install-extension ms-vscode.azure-account
code-insiders --install-extension formulahendry.auto-rename-tag
code-insiders --install-extension formulahendry.auto-close-tag
code-insiders --install-extension ms-python.anaconda-extension-pack
code-insiders --install-extension annsk.alignment
code-insiders --install-extension ms-vscode-remote.vscode-remote-extensionpack
code-insiders --install-extension GitHub.vscode-pull-request-github
code-insiders --install-extension vscode-org-mode.org-mode
code-insiders --install-extension Ikuyadeu.r-pack
code-insiders --install-extension shengchen.vscode-leetcode
code-insiders --install-extension fabiospampinato vscode-open-in-application
